# Generated by Django 4.1 on 2022-09-02 21:35

import cpf_field.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("farmer_name", models.CharField(max_length=128)),
                ("farmer_email", models.EmailField(max_length=254)),
                (
                    "farmer_cpf",
                    cpf_field.models.CPFField(max_length=14, verbose_name="cpf"),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("tillage_type", models.CharField(max_length=50)),
                ("harvest_date", models.DateField()),
                (
                    "cause",
                    models.CharField(
                        choices=[
                            ("Chuva excessiva", "Excessive Rain"),
                            ("Geada", "Frost"),
                            ("Granizo", "Hail"),
                            ("Seca", "Dry"),
                            ("Vendaval", "Windle"),
                            ("Raio", "Lightning"),
                        ],
                        max_length=15,
                    ),
                ),
                ("last_modified", models.DateField(auto_now=True)),
                (
                    "analyst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
